(ns kami-app-isekai.playtest.tuning
  "Playtest Co-Scientist — tuning knobs over public/games/slime-hunt/scene.edn's \"juice\"
  parameters (the SPECIFIC keys that don't require a WASM recompile of logic.cljc, since
  scene.edn is fetched at RUNTIME by dev/slime_hunt/game.cljs — `fetch-text \"public/games/
  slime-hunt/scene.edn\"` — not baked into dev/out/game.js at cljs-build time; editing it
  needs no `bb slime-hunt-build` between generations, only a page reload):

    :fx :burst :pick / :fx :burst :hit   — particle count/speed/gravity/life/size/colors
    :fx :shake                           — screen-shake amp/frames on hit
    :audio :pick/:hit/:victory/:gameover — each {:wave :freq :to :dur :gain}

  2026-07-09 kaizen: :wave (the oscillator-shape enum) is now ALSO tuned, as a small
  CATEGORICAL choice set (sine/square/sawtooth/triangle — the 4 real Web Audio
  OscillatorNode types every :wave value in this file already uses) rather than a numeric
  random-walk — see `categorical-choices`/`perturb` below. :colors (rgba palettes) remains
  deliberately untouched: a whole palette isn't a single categorical value the way :wave is,
  and a naive per-channel numeric walk on it would drift into muddy/clashing colors rather
  than a meaningfully different but still coherent palette — a real future pass here would
  need a small curated PALETTE choice set (several hand-picked coherent palettes to choose
  between), not a per-number perturbation, so it's left out of this pass too.

  Deliberately DOES NOT touch :world/:flow/:input/logic.cljc gameplay speeds/ranges/layout —
  those need a WASM recompile and/or change win/lose balance, explicitly out of scope for
  this pass (see scripts/playtest_coscientist.clj docstring; a documented follow-up, not
  built now).

  scene.edn is `pr-str`/`clojure.pprint`-able plain EDN (see scripts/gen_scene.clj's own
  `-main`) — read/write here go straight through `clojure.edn`/`pprint`, no template engine."
  ;; edn/pprint required unconditionally (not #?(:clj …)-gated): read-scene/write-scene!
  ;; below ARE :clj-only (the whole point — scene.edn is a JVM-side authoring artifact), but
  ;; gating the require itself per-branch make an all-:clj reader-conditional require list
  ;; elide to nothing on a :cljs read, which is a genuine (if lint-only, not a runtime) error
  ;; — an unconditional require + :clj-only usage is the simpler, still-correct shape.
  (:require [clojure.edn :as edn]
            [clojure.pprint :as pp]))

;; ───────────────────────── read / write scene.edn ─────────────────────────

#?(:clj
   (defn read-scene [path] (edn/read-string (slurp path))))

#?(:clj
   (defn write-scene!
     "Writes `scene` back to `path` as pretty-printed EDN, prefixed with the SAME
     do-not-hand-edit-the-composed-blocks header scripts/gen_scene.clj writes (this fn only
     ever touches :fx/:audio, never the composed :sprites/:render/profiles/:terrain blocks
     the header warns about, but the header documents the whole file's provenance, not just
     one writer, so it stays accurate regardless of which tool wrote the file last)."
     [path scene]
     (spit path
           (str ";; GENERATED by scripts/gen_scene.clj — do not hand-edit the composed :sprites/\n"
                ";; :render/profiles blocks (re-run `clojure -M:gen-scene` instead); :terrain/:hud/\n"
                ";; :flow/:input/:audio/:fx are hand-tunable game design data.\n"
                (with-out-str (pp/pprint scene))))))

;; ───────────────────────── the tunable slice ─────────────────────────

(def tunable-paths
  "Every scene.edn keypath this namespace will read/perturb/write — the exhaustive list, so
  `extract`/`apply-params` can't silently drift apart from each other."
  [[:fx :shake :amp] [:fx :shake :frames]
   [:fx :burst :pick :n] [:fx :burst :pick :spd] [:fx :burst :pick :grav]
   [:fx :burst :pick :life] [:fx :burst :pick :size]
   [:fx :burst :hit :n] [:fx :burst :hit :spd] [:fx :burst :hit :grav]
   [:fx :burst :hit :life] [:fx :burst :hit :size]
   [:audio :pick :freq] [:audio :pick :to] [:audio :pick :dur] [:audio :pick :gain] [:audio :pick :wave]
   [:audio :hit :freq] [:audio :hit :to] [:audio :hit :dur] [:audio :hit :gain] [:audio :hit :wave]
   [:audio :victory :freq] [:audio :victory :to] [:audio :victory :dur] [:audio :victory :gain] [:audio :victory :wave]
   [:audio :gameover :freq] [:audio :gameover :to] [:audio :gameover :dur] [:audio :gameover :gain] [:audio :gameover :wave]])

(defn extract
  "scene -> {keypath value} over tunable-paths only (:colors is left alone — see the
  namespace docstring for why; :wave IS included, tuned categorically — see perturb)."
  [scene]
  (into {} (map (fn [kp] [kp (get-in scene kp)])) tunable-paths))

(defn apply-params
  "{keypath value} -> scene with those (and only those) keypaths assoc'd in via assoc-in."
  [scene params]
  (reduce-kv (fn [s kp v] (assoc-in s kp v)) scene params))

;; ───────────────────────── perturbation bounds ─────────────────────────
;; Chosen bounds/rationale (documented per the task's own requirement — "don't let particle
;; count go negative or shake amplitude go absurdly high"):
;;   :n (particle count)     [3, 40]     — 0 would silently disable the burst entirely (not a
;;                                         "weaker" burst, a BUG-shaped regression); 40 is
;;                                         ~3x the current :hit n=14, comfortably above
;;                                         "visibly more" without becoming a full-screen
;;                                         sprite-fill performance/legibility problem.
;;   :spd (particle speed)   [0.5, 6.0]  — current values are 2.0/2.6; halves to doubles+ the
;;                                         spread radius, floor keeps particles from
;;                                         clumping invisibly at the origin.
;;   :grav                   [0.0, 0.4]  — 0 = particles fly straight (no arc, still valid);
;;                                         current values 0.10/0.16; 0.4 makes them slam back
;;                                         down almost immediately (still a valid, just
;;                                         "heavier", look) — no negative (upward-accelerating
;;                                         particles read as a bug, not a style).
;;   :life (frames)          [8, 60]     — below 8 frames (~0.13s@60fps) a burst is
;;                                         imperceptible; above 60 (~1s) particles start
;;                                         overlapping the NEXT beat's burst in fast play.
;;   :size (px)               [2, 14]    — current 5/6; 2 is barely visible (still a valid
;;                                         "subtle" data point for the co-scientist to learn
;;                                         is worse), 14 starts occluding entities.
;;   :shake :amp              [0, 30]    — 0 = no shake (valid); current 14; 30 is roughly
;;                                         double, still short of nauseating at :frames<=12.
;;   :shake :frames           [4, 24]    — current 12 (~0.2s@60fps); 4 reads as a flicker, 24
;;                                         (~0.4s) is close to the invuln window itself
;;                                         (45 ticks) — long enough to feel "heavy" without
;;                                         overlapping the NEXT possible hit's shake.
;;   :audio :freq/:to (Hz)    [80, 2000] — below 80Hz is sub-bass mud on typical laptop
;;                                         speakers, above 2000Hz gets shrill/tinny for a UI
;;                                         cue; current cues all fall well inside this band.
;;   :audio :dur (sec)        [0.05, 1.0]— below 0.05s is inaudible-click territory, above 1s
;;                                         a pickup/hit cue overstays a beat that repeats
;;                                         often (only :victory/:gameover currently use >0.4s,
;;                                         both one-shot end-states where a longer cue is fine
;;                                         — the shared bound is deliberately a bit generous
;;                                         for those two rather than adding two more bound
;;                                         tables).
;;   :audio :gain (0-1 linear)[0.05, 0.5]— below 0.05 is inaudible, above 0.5 risks clipping/
;;                                         being jarringly loud next to the other cues (all
;;                                         current gains are 0.15-0.22).
(def bounds
  {:n [3 40] :spd [0.5 6.0] :grav [0.0 0.4] :life [8 60] :size [2 14]
   :shake-amp [0 30] :shake-frames [4 24]
   :freq [80 2000] :dur [0.05 1.0] :gain [0.05 0.5]})

;; :wave (oscillator shape) — 2026-07-09: a small CATEGORICAL choice set, not a numeric
;; range. These are the 4 real Web Audio `OscillatorNode.type` values (`kami.audio`'s
;; synthesized sfx bank plays these directly, no others are valid) — every :wave value
;; already in scene.edn is one of these 4, so perturbing within this set can never produce
;; an invalid oscillator type.
(def categorical-choices
  {:wave ["sine" "square" "sawtooth" "triangle"]})

(defn- bound-for [kp]
  (let [leaf (last kp)]
    (cond
      (= kp [:fx :shake :amp]) (:shake-amp bounds)
      (= kp [:fx :shake :frames]) (:shake-frames bounds)
      (contains? bounds leaf) (get bounds leaf)
      :else nil)))

(defn- categorical-path? [kp] (contains? categorical-choices (last kp)))

(defn- clamp [[lo hi] v] (max lo (min hi v)))

(defn- integral-path?
  "Whether keypath `kp` holds an integer-valued param (particle count / frame counts / Hz /
  the guest-facing screen-shake ints) vs a float (speed/gravity/life-as-seconds/gain).
  scene.edn's own authored values are the ground truth for this (see public/games/
  slime-hunt/scene.edn: :n/:frames/:freq/:to are bare ints, :spd/:grav/:dur/:gain/:amp have
  decimal points) — matched here by leaf key name so a perturbed value round-trips as the
  same numeric type the file already uses, not a stray float where an int was."
  [kp]
  (contains? #{:n :life :size :frames :freq :to :amp} (last kp)))

;; ───────────────────────── candidate generation ─────────────────────────

(defn perturb
  "Generates ONE perturbed candidate params map from `baseline-params` (as returned by
  `extract`): each tunable value gets a random walk of ±`step-frac` of its own bound range
  (default 25% of [lo,hi]'s span — big enough that a generation is visibly different from
  the baseline in a single round given the small round budget, small enough that most
  candidates stay in a plausible neighborhood rather than jumping to the bound edges every
  time), clamped into its documented bound.

  `rng` is an injected java.util.Random-like `(fn [] -> double in [0,1))` — pure/testable,
  no hidden System/currentTimeMillis seed (matches this repo's `qa_governor.ledger`
  convention of injected non-deterministic inputs). For a categorical path (currently only
  :wave — see `categorical-choices`), this picks a DIFFERENT choice than the current value
  (never a no-op re-pick of the same wave) using the same `rng`, rather than a numeric walk."
  [baseline-params rng & {:keys [step-frac] :or {step-frac 0.25}}]
  (into {}
        (map (fn [[kp v]]
               (cond
                 (categorical-path? kp)
                 (let [choices (get categorical-choices (last kp))
                       others (vec (remove #(= % v) choices))
                       idx (int (Math/floor (* (rng) (count others))))]
                   [kp (if (seq others) (nth others idx) v)])

                 :else
                 (let [b (bound-for kp)]
                   (if (nil? b)
                     [kp v]
                     (let [[lo hi] b
                           span (- hi lo)
                           delta (* span step-frac (- (* 2.0 (rng)) 1.0)) ;; in [-span*step-frac, +span*step-frac]
                           raw (+ v delta)
                           clamped (clamp b raw)
                           out (if (integral-path? kp) (long (Math/round (double clamped))) (double clamped))]
                       [kp out])))))
        baseline-params)))

(defn candidate-scene
  "baseline scene + a freshly perturbed params map -> a new scene (baseline untouched)."
  [baseline-scene rng & opts]
  (apply-params baseline-scene (apply perturb (extract baseline-scene) rng opts)))
